# Generated by Django 4.2.7 on 2023-11-18 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TalentHunt_Web', '0003_hunter2_project2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('years_of_experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('availability', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.ManyToManyField(related_name='talents', to='TalentHunt_Web.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_skills', models.CharField(max_length=300)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_duration', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=20)),
                ('hunter_name', models.CharField(max_length=200)),
                ('hunter_email', models.EmailField(max_length=254)),
                ('hunter_phone', models.CharField(max_length=20)),
                ('contract_id', models.IntegerField()),
                ('terms', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalentHunt_Web.talent')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_skills', models.CharField(max_length=300)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_duration', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=20)),
                ('terms', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='TalentHunt_Web.hunter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalentHunt_Web.project')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='TalentHunt_Web.talent')),
            ],
        ),
    ]
